### ISSUE TITLE
Cant clear settings

### ISSUE THREAD

**Issue by d0x360** [zlepper/GameLoader#10]
If drive letters are changed there is no obvious way to "refresh" the app and start new.  Uninstalling doesnt work.

**Comment by zlepper** [comment]
Ehhm, i don't quite follow, clear what settings?

**Comment by d0x360** [comment]
All of them. For example I changed my drive E to D.  Ita still showing
everything as drive E.  There should be a way to empty the game list.

Where does the app store its settings, I'll do it that way.

**Comment by zlepper** [comment]
Ohh, it's stored in %appdata%\local I recall.
Also I haven't really considered people changing the drive letter without deleting reseting the entire computer.

**Comment by d0x360** [comment]
The upgrade to windows 10 can do it.  So can doing system restores for some
reason.

**Comment by zlepper** [comment]
Right well, I have no good way of detecting it happening, so not much I can do without checking for all the directories' status on startup.
Also wouldn't the path get messed up when drive letters change anyway?

But I can look it doing something about it next month. Im all hung up this month.

**Comment by d0x360** [comment]
You could just add a reset all button.  As for windows pathing there are
some things you need to edit but it takes about 5 min and the OS does the
rest for you.
