### ISSUE TITLE
Full screen Table

### ISSUE THREAD

**Issue by d0x360** [zlepper/GameLoader#5]
If you make the app full screen the table stays tiny.  It should fill the whole window of the app even if it isnt full of games otherwise it looks silly, 
![fullscr](https://cloud.githubusercontent.com/assets/14056857/9678545/5efdb29e-52b4-11e5-81bb-dbd65e0b36da.png)

**Comment by zlepper** [comment]
Will release a build with this later. Not much that can brake in that single line of code I added.
