### ISSUE TITLE
Better scans for game folders

### ISSUE THREAD

**Issue by d0x360** [zlepper/GameLoader#8]
D: drive is only showing one game when in reality I have about 3 TB of games on that drive. So the startup scan I think it did wasn't accurate in finding steam folders.

Scanning every folder for steam common folders might now be an option but the games it missed were in D:\SteamLibrary instead of the common Program Files/Steam Directory. So perhaps it could scan root and program files for the word steam, origin etc.

**Comment by zlepper** [comment]
Right now it just has some default paths it checks on all drives, but doing a proper search would likely be better.

**Comment by zlepper** [comment]
Will release a build with this later, once I have done a bit more testing.

**Comment by d0x360** [comment]
Nice!  It's not requires feature but I think 90% of gamers are totally
computer illiterate NFL open a program and don't understand immediately
they close it and delete it. They won't spend the time that I did trying to
figure everything out and all that stuff to making it as easy as possible
will go a long way to get people to using it. If you decide to do you some
of my suggestions and I feel the program is at a level where the average
person could easily play around with it I will start helping promote it and
I'm very good at promotion on the Internet. Also if anything I just said
above makes no sense it's because I used google voice dictation and I
didn't pre read it before I hit Send I'm sorry I can't help it I'm playing
Forza 6
